### ISSUE TITLE
Add support for Kerberos encrypted SOAP-messages

### ISSUE THREAD

**Issue by Lennie** [zenoss/txwinrm#1]
If I'm not mistaken Kerberos encrypted SOAP messages is the default with quickconfig it obviously also is encrypted thus safer.

It took me some time to figure out how Kerberos fitted into all this and what was and wasn't possible. And when I did I found an open source implementation that probably works.

Here is an example of what it looks like:
http://msdn.microsoft.com/en-us/library/cc251724.aspx

At the most basic level, when a Kerberos-authenticated connection/session has been established, you can ask the Kerberos GSS-API/library to encrypt messages on your behave. It's called 'wrapping'. When you receive a message you do the opposite, you 'unwrap' the message.

Here is the open source implementation in Ruby:

https://github.com/WinRb/WinRM/blob/master/lib/winrm/http/transport.rb

Here is the conversation that helped the open source developer to get it to work:
http://social.msdn.microsoft.com/Forums/en-US/os_windowsprotocols/thread/db7ab0da-3bee-4965-a03f-0e3316e606da

I hope a call to authGSSClientWrap will be enough, but it wasn't what was needed in the case of the Ruby implementation, so I'm not a 100% sure the Python Kerberos GSSAPI-library currently in use by txwinrm would be sufficient, because it does not seem to support passing buffers.

The developer that wrote the WinRM implementation also created a GSSAPI library for Ruby:

https://github.com/zenchild/gssapi

Which could be used as an example for creating a similair Python library or extending the existing Kerberos library if needed.

**Comment by dbouchillon** [comment]
This has been added.  closing issue
